### ISSUE TITLE
Can't access last edit information

### ISSUE THREAD

**Issue by jdlrobson** [joakin/loot#40]

**Comment by joakin** [comment]
I've commented on the loot-ui pr with some thoughts: https://github.com/joakin/loot-ui/pull/32#issuecomment-164424914

And also https://github.com/joakin/loot-ui/pull/32#issuecomment-164425692 since it seems like that info is already on the document so we can return it from the `/slim` endpoints directly extracted from the restbase html.

Should we chat over there?
